### ISSUE TITLE
BPTK as conda package?

### ISSUE THREAD

**Issue by adrien-perello** [transentis/bptk_py_tutorial#1]
I use Anaconda to manage my virtual environments and packages, and to run jupyter.

As far as I understand, using ```pip``` and ```conda``` is bad practice. So I was trying to build a BPTK-py package with ```conda-build``` and ```conda-skeleton``` ([more info here](https://conda.io/projects/conda-build/en/latest/user-guide/tutorials/build-pkgs-skeleton.html)).  But my knowledge is limited and I ran in a problem (as you can see below in the attached image) following the command ```conda skeleton pypi BPTK-Py``` .

I believe the build failed when trying to import the module [conf](https://pypi.org/project/conf/). I tried to do this part manually (also by using ```conda-skeleton```) but it failed too.

**My question is**: Have you considered releasing a conda package of BPTK-py? I believe this could be really useful given the importance anaconda has taken in the data science community.

![Screenshot from 2021-05-04 08-46-29](https://user-images.githubusercontent.com/76055749/116969649-e91dc600-acb6-11eb-8a53-21e160e92ac5.png)

**Comment by olivergrasl** [comment]
Hello Adrien,

Thank you for getting in touch – we have a number of users who install BPTK-Py with conda using pip (https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#using-pip-in-an-environment) and that is probably the quickest way for now.

But I like your idea of providing a conda package for bptk-py  and we will look into this asap, as it shouldn’t be a big issue.

Best,

Oliver

PS: the quickest way of getting in touch with us regarding bptk is via ***@***.******@***.***>


Von: adrien-perello ***@***.***>
Antworten an: transentis/bptk_py_tutorial ***@***.***>
Datum: Dienstag, 4. Mai 2021 um 09:08
An: transentis/bptk_py_tutorial ***@***.***>
Cc: Subscribed ***@***.***>
Betreff: [transentis/bptk_py_tutorial] BPTK as conda package? (#1)


I use Anaconda to manage my virtual environments and packages, and to run jupyter.

As far as I understand, using pip and conda is bad practice. So I was trying to build a BPTK-py package with conda-build and conda-skeleton (more info here<https://conda.io/projects/conda-build/en/latest/user-guide/tutorials/build-pkgs-skeleton.html>). But my knowledge is limited and I ran in a problem (as you can see below in the attached image) following the command conda skeleton pypi BPTK-Py .

I believe the build failed when trying to import the module conf<https://pypi.org/project/conf/>. I tried to do this part manually (also by using conda-skeleton) but it failed too.

My question is: Have you considered releasing a conda package of BPTK-py? I believe this could be really useful given the importance anaconda has taken in the data science community.

[Screenshot from 2021-05-04 08-46-29]<https://user-images.githubusercontent.com/76055749/116969649-e91dc600-acb6-11eb-8a53-21e160e92ac5.png>
