### ISSUE TITLE
some probel in abm_spm_agent_dc.json

### ISSUE THREAD

**Issue by 783010296** [transentis/bptk_py_tutorial#2]
hello
when i learn bptk_py，i find some problem in abm_spm_agent_dc.json
\abm\how-to\how_to_choose_datacollector\scenarios\abm_spm_agent_dc.json
What is the meaning of this variable？I didn't find an explanation
![image](https://user-images.githubusercontent.com/15160126/144387102-f4643329-76c1-4c9a-a115-32d52bcba24c.png)

**Comment by olivergrasl** [comment]
hello,
dt is "delta time" - the simulation runs in rounds. the number of rounds is equal to stoptime-starttime.

within each round, there are a number of steps. the number of steps per round  is equal to 1/dt (typically dt is therefore a fraction of one, e.g. 1/4=0.25).

thus the "model time" is then always equal to:

time = round-number + dt* step_number

so if your starttime=0, stoptime=120 and dt=0.25, the model will run in the following timesteps:

0,0.25,0.5,0.75,1.0,1.25,.... 119.75,120

we will improve our documentation regarding this!

best,

oliver

**Comment by 783010296** [comment]
thank you for help me
but i find another problem, please see my code 

![image](https://user-images.githubusercontent.com/15160126/144561885-0b09bdf4-7d19-434f-89b6-beac3030e0a5.png)

![image](https://user-images.githubusercontent.com/15160126/144562001-7bba7a2d-9417-468d-87b4-70d5bec51306.png)

![image](https://user-images.githubusercontent.com/15160126/144561946-8d6635fb-5b98-4f72-b7a8-8c3e0bfacf6f.png)

why the "80 Tasks, one step per time unit" line is diffience ?

**Comment by olivergrasl** [comment]
hi,

what exactly do you mean by "different"? - have you checked the underlying data? Don't forget the graph has fewer datapoints than the other one, so it "looks" slightly different.

**Comment by 783010296** [comment]
oh! i understand, thank you
